#!/bin/bash

# Check if there is a partition labeled ROOT and, if so, determine its UUID.
match=$(lsblk -o UUID,PARTLABEL | grep -w ROOT)
if [[ $? -ne 0 ]]; then
    exit 0
fi
uuid="${match%% *}"

# Check if the partition labeled ROOT is a LUKS device.
IFS= read -r -n "4" header < /dev/disk/by-uuid/$uuid
if [[ "$header" != "LUKS" ]]; then
    exit 0
fi

# Generate a systemd-cryptsetup unit to decrypt the root partition.
# We call the LUKS device `rootencrypted`, no matter what it was called in the Ignition configuration.
echo "rootencrypted UUID=$uuid none luks" > /tmp/crypttab
SYSTEMD_CRYPTTAB=/tmp/crypttab /usr/lib/systemd/system-generators/systemd-cryptsetup-generator /etc/systemd/system/

# Start the generated systemd service to decrypt the root partition.
systemctl start systemd-cryptsetup@rootencrypted